apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    {{- if and (hasKey .Values "service") (hasKey .Values.service "ports") }}
      {{- range .Values.service.ports }}
      - name: {{ .name | default "http" }}
        port: {{ .port | default 80 }}
        targetPort: {{ .targetPort | default 80 }}
        protocol: {{ .protocol | default "TCP" }}
      {{- end }}
    {{- else if and (hasKey .Values "service") (hasKey .Values.service "port") }}
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 80 }}
      protocol: TCP
    {{- end }}
